exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    interface Product @nodeInterface {
      id: ID!
      name: String!
      slug: String!
      description: String
      photo: File
      categories: [Category!]!
    }

    interface Category @nodeInterface {
      id: ID!
      name: String!
      slug: String!

      # should be autogenerated - either via source plugin or via custom resolver
      # should NOT actually be in source content model/type
      products: [Product]!
    }
  `);
};
